package engine

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
)

// pgLiteral quotes a string literal the way quote_literal() does: an E”
// string when backslashes are present, so the result is correct whatever
// standard_conforming_strings is set to.
func pgLiteral(s string) string {
	q := strings.ReplaceAll(s, "'", "''")
	if strings.Contains(s, `\`) {
		return "E'" + strings.ReplaceAll(q, `\`, `\\`) + "'"
	}
	return "'" + q + "'"
}

// pgTableRef quotes "schema.table" or "table" (defaulting to schema).
func pgTableRef(name, defaultSchema string) string {
	if s, t, ok := strings.Cut(name, "."); ok && s != "" && t != "" {
		return qualifiedTable(s, t)
	}
	return qualifiedTable(defaultSchema, name)
}

func pgColumnDef(c ColumnSpec) (string, error) {
	if err := validName("column", c.Name); err != nil {
		return "", err
	}
	typ, err := checkType(pgTypeRe, c.Type)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "%s %s", quotePGIdent(c.Name), typ)
	if !c.Nullable {
		b.WriteString(" NOT NULL")
	}
	def, err := renderDefault(c, pgLiteral)
	if err != nil {
		return "", err
	}
	if c.AutoIncrement {
		if !intTypeRe.MatchString(typ) {
			return "", fmt.Errorf("auto increment needs an integer column, not %s", typ)
		}
		if def != "" {
			return "", fmt.Errorf("an identity column cannot also have a default")
		}
		b.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
	}
	b.WriteString(def)
	return b.String(), nil
}

// ddlTx runs statements in one transaction — PostgreSQL DDL is transactional,
// so a multi-step change applies completely or not at all.
func (pg *Postgres) ddlTx(ctx context.Context, p ConnParams, database string,
	build func(ctx context.Context, conn *pgx.Conn) ([]string, error)) error {
	if !identRe.MatchString(database) {
		return fmt.Errorf("invalid database name")
	}
	conn, err := pg.connect(ctx, p, database)
	if err != nil {
		return err
	}
	defer conn.Close(ctx)
	stmts, err := build(ctx, conn)
	if err != nil {
		return err
	}
	tx, err := conn.Begin(ctx)
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback(ctx) }()
	for _, s := range stmts {
		if _, err := tx.Exec(ctx, s); err != nil {
			return err
		}
	}
	return tx.Commit(ctx)
}

// resolved resolves "schema.table" to its quoted form and schema.
func (pg *Postgres) resolved(ctx context.Context, conn *pgx.Conn, table string) (string, string, error) {
	if !validTableName(table) {
		return "", "", fmt.Errorf("invalid table name")
	}
	schema, name, err := pg.resolveTable(ctx, conn, table)
	if err != nil {
		return "", "", err
	}
	return qualifiedTable(schema, name), schema, nil
}

// CreateTable creates a table. spec.Name may be "schema.table"; the default
// schema is public.
func (pg *Postgres) CreateTable(ctx context.Context, p ConnParams, database string, spec TableSpec) error {
	schema, name := "public", spec.Name
	if s, t, ok := strings.Cut(spec.Name, "."); ok {
		schema, name = s, t
		if err := existingName("schema", schema); err != nil {
			return err
		}
	}
	if err := validName("table", name); err != nil {
		return err
	}
	if len(spec.Columns) == 0 {
		return fmt.Errorf("a table needs at least one column")
	}
	q := qualifiedTable(schema, name)
	return pg.ddlTx(ctx, p, database, func(context.Context, *pgx.Conn) ([]string, error) {
		var parts, after []string
		for _, c := range spec.Columns {
			def, err := pgColumnDef(c)
			if err != nil {
				return nil, err
			}
			parts = append(parts, def)
			if c.Comment != "" {
				after = append(after, fmt.Sprintf("COMMENT ON COLUMN %s.%s IS %s", q, quotePGIdent(c.Name), pgLiteral(c.Comment)))
			}
		}
		if len(spec.PrimaryKey) > 0 {
			cols, err := quotedList(spec.PrimaryKey, quotePGIdent)
			if err != nil {
				return nil, err
			}
			parts = append(parts, "PRIMARY KEY ("+strings.Join(cols, ", ")+")")
		}
		for _, fk := range spec.ForeignKeys {
			clause, err := renderFK(fk, quotePGIdent, func(t string) string { return pgTableRef(t, schema) })
			if err != nil {
				return nil, err
			}
			parts = append(parts, clause)
		}
		stmts := []string{fmt.Sprintf("CREATE TABLE %s (\n  %s\n)", q, strings.Join(parts, ",\n  "))}
		if spec.Comment != "" {
			stmts = append(stmts, fmt.Sprintf("COMMENT ON TABLE %s IS %s", q, pgLiteral(spec.Comment)))
		}
		return append(stmts, after...), nil
	})
}

// AlterTable applies ops in one transaction.
func (pg *Postgres) AlterTable(ctx context.Context, p ConnParams, database, table string, ops []AlterOp) error {
	if len(ops) == 0 {
		return fmt.Errorf("no changes")
	}
	return pg.ddlTx(ctx, p, database, func(ctx context.Context, conn *pgx.Conn) ([]string, error) {
		q, schema, err := pg.resolved(ctx, conn, table)
		if err != nil {
			return nil, err
		}
		var stmts []string
		alter := func(clause string) { stmts = append(stmts, "ALTER TABLE "+q+" "+clause) }
		for _, op := range ops {
			switch op.Op {
			case AlterAddColumn:
				if op.Column == nil {
					return nil, fmt.Errorf("add_column needs a column")
				}
				def, err := pgColumnDef(*op.Column)
				if err != nil {
					return nil, err
				}
				alter("ADD COLUMN " + def)
				if op.Column.Comment != "" {
					stmts = append(stmts, fmt.Sprintf("COMMENT ON COLUMN %s.%s IS %s", q, quotePGIdent(op.Column.Name), pgLiteral(op.Column.Comment)))
				}
			case AlterDropColumn:
				if err := existingName("column", op.Name); err != nil {
					return nil, err
				}
				alter("DROP COLUMN " + quotePGIdent(op.Name))
			case AlterModifyColumn:
				if op.Column == nil {
					return nil, fmt.Errorf("modify_column needs a column")
				}
				if err := existingName("column", op.Name); err != nil {
					return nil, err
				}
				c := *op.Column
				if err := validName("column", c.Name); err != nil {
					return nil, err
				}
				typ, err := checkType(pgTypeRe, c.Type)
				if err != nil {
					return nil, err
				}
				col := quotePGIdent(op.Name)
				if c.Name != op.Name {
					alter("RENAME COLUMN " + col + " TO " + quotePGIdent(c.Name))
					col = quotePGIdent(c.Name)
				}
				alter(fmt.Sprintf("ALTER COLUMN %s TYPE %s USING %s::%s", col, typ, col, typ))
				if c.Nullable {
					alter("ALTER COLUMN " + col + " DROP NOT NULL")
				} else {
					alter("ALTER COLUMN " + col + " SET NOT NULL")
				}
				if !c.KeepDefault {
					def, err := renderDefault(c, pgLiteral)
					if err != nil {
						return nil, err
					}
					if def == "" {
						alter("ALTER COLUMN " + col + " DROP DEFAULT")
					} else {
						alter("ALTER COLUMN " + col + " SET" + def)
					}
				}
				if c.Comment != "" {
					stmts = append(stmts, fmt.Sprintf("COMMENT ON COLUMN %s.%s IS %s", q, col, pgLiteral(c.Comment)))
				}
			case AlterRenameColumn:
				if err := existingName("column", op.Name); err != nil {
					return nil, err
				}
				if err := validName("column", op.NewName); err != nil {
					return nil, err
				}
				alter("RENAME COLUMN " + quotePGIdent(op.Name) + " TO " + quotePGIdent(op.NewName))
			case AlterAddForeignKey:
				if op.ForeignKey == nil {
					return nil, fmt.Errorf("add_foreign_key needs a foreign key")
				}
				clause, err := renderFK(*op.ForeignKey, quotePGIdent, func(t string) string { return pgTableRef(t, schema) })
				if err != nil {
					return nil, err
				}
				alter("ADD " + clause)
			case AlterDropForeignKey:
				if err := existingName("constraint", op.Name); err != nil {
					return nil, err
				}
				alter("DROP CONSTRAINT " + quotePGIdent(op.Name))
			default:
				return nil, fmt.Errorf("unsupported alter operation %q", op.Op)
			}
		}
		return stmts, nil
	})
}

// DropTable drops a table.
func (pg *Postgres) DropTable(ctx context.Context, p ConnParams, database, table string) error {
	return pg.ddlTx(ctx, p, database, func(ctx context.Context, conn *pgx.Conn) ([]string, error) {
		q, _, err := pg.resolved(ctx, conn, table)
		return []string{"DROP TABLE " + q}, err
	})
}

// TruncateTable removes every row.
func (pg *Postgres) TruncateTable(ctx context.Context, p ConnParams, database, table string) error {
	return pg.ddlTx(ctx, p, database, func(ctx context.Context, conn *pgx.Conn) ([]string, error) {
		q, _, err := pg.resolved(ctx, conn, table)
		return []string{"TRUNCATE TABLE " + q}, err
	})
}

// RenameTable renames a table within its schema.
func (pg *Postgres) RenameTable(ctx context.Context, p ConnParams, database, table, newName string) error {
	if err := validName("table", newName); err != nil {
		return err
	}
	return pg.ddlTx(ctx, p, database, func(ctx context.Context, conn *pgx.Conn) ([]string, error) {
		q, _, err := pg.resolved(ctx, conn, table)
		return []string{"ALTER TABLE " + q + " RENAME TO " + quotePGIdent(newName)}, err
	})
}

// CreateIndex creates an index.
func (pg *Postgres) CreateIndex(ctx context.Context, p ConnParams, database, table string, spec IndexSpec) error {
	if err := validName("index", spec.Name); err != nil {
		return err
	}
	if len(spec.Columns) == 0 {
		return fmt.Errorf("an index needs at least one column")
	}
	cols, err := quotedList(spec.Columns, quotePGIdent)
	if err != nil {
		return err
	}
	unique := ""
	if spec.Unique {
		unique = "UNIQUE "
	}
	return pg.ddlTx(ctx, p, database, func(ctx context.Context, conn *pgx.Conn) ([]string, error) {
		q, _, err := pg.resolved(ctx, conn, table)
		return []string{fmt.Sprintf("CREATE %sINDEX %s ON %s (%s)", unique, quotePGIdent(spec.Name), q, strings.Join(cols, ", "))}, err
	})
}

// DropIndex drops an index; one that backs a constraint (primary key, unique
// constraint) is dropped by dropping the constraint.
func (pg *Postgres) DropIndex(ctx context.Context, p ConnParams, database, table, index string) error {
	if err := existingName("index", index); err != nil {
		return err
	}
	return pg.ddlTx(ctx, p, database, func(ctx context.Context, conn *pgx.Conn) ([]string, error) {
		q, schema, err := pg.resolved(ctx, conn, table)
		if err != nil {
			return nil, err
		}
		var constraint *string
		if err := conn.QueryRow(ctx, `
			SELECT con.conname FROM pg_constraint con
			JOIN pg_class i ON i.oid = con.conindid
			JOIN pg_namespace n ON n.oid = i.relnamespace
			WHERE n.nspname = $1 AND i.relname = $2`, schema, index).Scan(&constraint); err != nil && !errors.Is(err, pgx.ErrNoRows) {
			return nil, err
		}
		if constraint != nil {
			return []string{"ALTER TABLE " + q + " DROP CONSTRAINT " + quotePGIdent(*constraint)}, nil
		}
		return []string{"DROP INDEX " + qualifiedTable(schema, index)}, nil
	})
}

// ForeignKeys lists a table's outgoing foreign keys.
func (pg *Postgres) ForeignKeys(ctx context.Context, p ConnParams, database, table string) ([]ForeignKey, error) {
	if !identRe.MatchString(database) {
		return nil, fmt.Errorf("invalid database name")
	}
	conn, err := pg.connect(ctx, p, database)
	if err != nil {
		return nil, err
	}
	defer conn.Close(ctx)
	if !validTableName(table) {
		return nil, fmt.Errorf("invalid table name")
	}
	schema, name, err := pg.resolveTable(ctx, conn, table)
	if err != nil {
		return nil, err
	}
	rows, err := conn.Query(ctx, `
		SELECT con.conname,
		       ARRAY(SELECT a.attname FROM unnest(con.conkey) WITH ORDINALITY k(n, o)
		             JOIN pg_attribute a ON a.attrelid = con.conrelid AND a.attnum = k.n ORDER BY k.o),
		       rn.nspname || '.' || rc.relname,
		       ARRAY(SELECT a.attname FROM unnest(con.confkey) WITH ORDINALITY k(n, o)
		             JOIN pg_attribute a ON a.attrelid = con.confrelid AND a.attnum = k.n ORDER BY k.o),
		       CASE con.confdeltype WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'r' THEN 'RESTRICT'
		            WHEN 'd' THEN 'SET DEFAULT' ELSE 'NO ACTION' END,
		       CASE con.confupdtype WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'r' THEN 'RESTRICT'
		            WHEN 'd' THEN 'SET DEFAULT' ELSE 'NO ACTION' END
		FROM pg_constraint con
		JOIN pg_class c ON c.oid = con.conrelid
		JOIN pg_namespace n ON n.oid = c.relnamespace
		JOIN pg_class rc ON rc.oid = con.confrelid
		JOIN pg_namespace rn ON rn.oid = rc.relnamespace
		WHERE con.contype = 'f' AND n.nspname = $1 AND c.relname = $2
		ORDER BY con.conname`, schema, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []ForeignKey{}
	for rows.Next() {
		var fk ForeignKey
		if err := rows.Scan(&fk.Name, &fk.Columns, &fk.RefTable, &fk.RefColumns, &fk.OnDelete, &fk.OnUpdate); err != nil {
			return nil, err
		}
		out = append(out, fk)
	}
	return out, rows.Err()
}

// Objects lists views, materialized views, functions, procedures, triggers and
// sequences outside the system schemas.
func (pg *Postgres) Objects(ctx context.Context, p ConnParams, database string) ([]DBObject, error) {
	if !identRe.MatchString(database) {
		return nil, fmt.Errorf("invalid database name")
	}
	conn, err := pg.connect(ctx, p, database)
	if err != nil {
		return nil, err
	}
	defer conn.Close(ctx)
	const userSchema = `NOT IN ('pg_catalog','information_schema') AND %s NOT LIKE 'pg\_toast%%' AND %s NOT LIKE 'pg\_temp%%'`
	us := func(col string) string { return col + " " + fmt.Sprintf(userSchema, col, col) }
	rows, err := conn.Query(ctx, `
		SELECT 'view', schemaname, viewname, NULL, pg_get_viewdef(format('%I.%I', schemaname, viewname)::regclass, true)
		  FROM pg_views WHERE `+us("schemaname")+`
		UNION ALL
		SELECT 'materialized_view', schemaname, matviewname, NULL, definition
		  FROM pg_matviews WHERE `+us("schemaname")+`
		UNION ALL
		SELECT CASE p.prokind WHEN 'p' THEN 'procedure' ELSE 'function' END, n.nspname,
		       p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')', NULL, pg_get_functiondef(p.oid)
		  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
		  LEFT JOIN pg_depend d ON d.objid = p.oid AND d.deptype = 'e'
		 WHERE p.prokind IN ('f','p') AND d.objid IS NULL AND `+us("n.nspname")+`
		UNION ALL
		SELECT 'trigger', n.nspname, t.tgname, c.relname, pg_get_triggerdef(t.oid, true)
		  FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace n ON n.oid = c.relnamespace
		 WHERE NOT t.tgisinternal AND `+us("n.nspname")+`
		UNION ALL
		SELECT 'sequence', schemaname, sequencename, NULL, NULL
		  FROM pg_sequences WHERE `+us("schemaname")+`
		ORDER BY 1, 2, 3`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []DBObject{}
	for rows.Next() {
		var o DBObject
		var kind string
		var table *string
		if err := rows.Scan(&kind, &o.Schema, &o.Name, &table, &o.Definition); err != nil {
			return nil, err
		}
		o.Kind = ObjectKind(kind)
		if table != nil {
			o.Table = *table
		}
		o.Definition = truncateDefinition(o.Definition)
		out = append(out, o)
	}
	return out, rows.Err()
}
